repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-aws-credentials
        args: ['--allow-missing-credentials']
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: flake8
    -   id: mixed-line-ending
        args: ['--fix=no']
    -   id: name-tests-test
        args: ['--django']
    -   id: no-commit-to-branch
        args: [--branch, master]
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.1.0
    hooks:
    -   id: python-use-type-annotations
